#! /bin/sh

## Install Nix
curl -L https://nixos.org/nix/install | sh -s -- --daemon

## The shell needs to be reloaded. Since this is a script, we can't do that.
## Instead, just running the commands within a subshell should do the trick.

# This is required after Nix is installed.
(nix-shell -p nix-info --run "nix-info -m")
sleep 2

# Install Home Manager
(nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager)
sleep 2
(nix-channel --update)
sleep 2
(
export NIX_CONFIG="experimental-features = nix-command flakes"
nix-shell '<home-manager>' -A install
)
sleep 2

# Make sure required directories exist
mkdir -p $HOME/.config/
mkdir -p $HOME/.config/fontconfig/conf.d/
mkdir -p $HOME/.local/share/fonts/

# Download fonts
wget https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
wget https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf

# Move them to the proper locations and load them
mv PowerlineSymbols.otf ~/.local/share/fonts/
mv 10-powerline-symbols.conf ~/.config/fontconfig/conf.d/
fc-cache -vf ~/.local/share/fonts

# Load Home
(
export NIX_CONFIG="experimental-features = nix-command flakes"
git clone --recurse-submodules https://github.com/theLockesmith/home-manager.git $HOME/.config/home-manager
home-manager switch -b backup
)

# Reload the shell
exec bash -l
