#! /bin/bash
if type shuf > /dev/null; then
  cowfile="$(neo-cowsay -l | sed "1 d" | tr ' ' '\n' | shuf -n 1)"
else
  cowfiles=( $(neo-cowsay -l | sed "1 d") );
  cowfile=${cowfiles[$(($RANDOM % ${#cowfiles[*]}))]}
fi
neo-cowsay -f "$cowfile"